name: Main

on: [push, pull_request]

jobs:
  test-tempate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Set up environment
      run: |
        python -m pip install --upgrade pip
        pip install -U cookiecutter poetry

    - name: Try to use template
      run: |
        cd ..
        cookiecutter --no-input ./cookiecutter-python-template
        cd awesomium
        poetry install
        make check-code-style
        make test
        make test-report
        make check-fixtures
        make reformat-files

    - name: Try to build the template
      run: |
        cd ..
        rm -rf awesomium
        cookiecutter --no-input ./cookiecutter-python-template
        cd awesomium
        docker build -t awesomium .
        docker run --rm awesomium
